config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :complaints
  devise_scope :user do
   get "", to: "devise/sessions#new"
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  
  has_many :taggings
  has_many :tags, through: :taggings

  validates :subject,:matter,:key_words, presence: true

  acts_as_taggable

  scope :with_tag_ids, lambda{ |tag_ids|
  # get a reference to the join table
  #role_assignments = Tagging.arel_table
  # get a reference to the filtered table
  #complaints = Complaint.arel_table
  # let AREL generate a complex SQL query
  #byebug
  #where(
    #Tagging \
      #.where(role_assignments[:taggable_id].eq(complaints[:id])) \
      #.where(role_assignments[:tag_id].in([*tag_ids].map(&:to_i))) \
      #.exists
  #)
    num_or_conds = 2
    item = tag_ids.downcase.split(/,/)
    item = item.map{|val| val.strip}
    #Tag.where(item.map{|tagid| "(name like ?)%"+tagid+"%"})
  #Tag.where(item.map{|tagid| "(name like ?)"}.join(' OR '),item.map{|e| '%'+e+'%'}.flatten)
    tag = Tag.where(item.map{|tagid| "(name like ?)"}.join(' OR '),*item.map{|e| '%'+e+'%'}.flatten)
    tagging = Tagging.where(tag_id: tag.map{|t|  t.id}).pluck(:taggable_id)
    where(id: tagging)
  }

  scope :search_query, lambda { |subject|
    return nil  if subject.blank?
    terms = subject.downcase.split(/\s+/)
    terms = terms.map { |e| '%'+e+'%'}
    num_or_conds = 2
    where(terms.map { |term| "(LOWER(complaints.subject) LIKE ? OR LOWER(complaints.subject) LIKE ?)" }.join(' AND '),
    *terms.map { |e| [e] * num_or_conds }.flatten)
  }

  scope :with_key_words, lambda { |key_words|
    where(key_words: [*key_words])
  }

  filterrific(
    # default_settings: { sorted_by: 'created_at_desc' },
    filter_names: [
      :search_query,
      :with_key_words,
      :with_tag_ids
    ]
  )
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base

  belongs_to :complaint
  belongs_to :tag

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :confirmable
  validate  :email_regex
  devise :omniauthable, :omniauth_providers => [:facebook]
  after_create :send_admin_mail

  def send_admin_mail
    UserMailer.send_new_user_message(self).deliver
  end

   def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def email_regex
    flag = 0
    comp = Company.uniq.pluck(:email_format)
    comp.each do |com|
      if email.present? and email.include? com
        flag = 1
        break
      end
    end
    unless flag == 1
      errors.add :email, " is not a valid"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    session[:previous_url] || complaints_path
  end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    # @complaints = Complaint.all
    @filterrific = Filterrific.new(Complaint, params[:filterrific])
    @complaints = Complaint.filterrific_find(@filterrific).page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:subject, :matter, :key_words, :filterrific, :tag_list)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/views/complaints/_form.html.erb
<%= form_for @complaint, :html => { :class => "form-horizontal complaint" } do |f| %>

  <% if @complaint.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@complaint.errors.count, "error") %> prohibited this complaint from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @complaint.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :subject, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :subject, :class => 'form-control' %>
    </div>
    <%=f.error_span(:subject) %>
  </div>
  <div class="form-group">
    <%= f.label :matter, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :matter, :class => 'form-control' %>
    </div>
    <%=f.error_span(:matter) %>
  </div>
  <div class="form-group">
    <%= f.label :key_words, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :key_words, :class => 'form-control' %>
    </div>
    <%=f.error_span(:key_words) %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :tag_list, :class => 'form-control' %>
    </div>
    <%=f.error_span(:tag_list) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                complaints_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/complaints/_list.html.erb
<%- model_class = Complaint -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:subject) %></th>
      <th><%= model_class.human_attribute_name(:matter) %></th>
      <th><%= model_class.human_attribute_name(:key_words) %></th>
      <th><%= model_class.human_attribute_name(:tag_list) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% complaints.each do |complaint| %>
      <tr>
        <td><%= link_to complaint.id, complaint_path(complaint) %></td>
        <td><%= complaint.subject %></td>
        <td><%= complaint.matter %></td>
        <td><%= complaint.key_words %></td>
        <td><%= complaint.tag_list %></td>
        <td><%=l complaint.created_at %></td>
        <td style="width: 107px;">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_complaint_path(complaint), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      complaint_path(complaint),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate complaints %>

app/views/complaints/edit.html.erb
<%- model_class = Complaint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/complaints/index.html.erb
<%- model_class = Complaint -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_for @filterrific do |f| %>
  <div style="float: left;margin-right: 39px;">
    Search
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
  <div style="float: left;margin-left: 10px;margin-right: 39px;">
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    key words
    <%= f.text_field(
      :with_key_words,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
  <div style="margin-left: 10px;">
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    Tags
    <%= f.text_field(
      :with_tag_ids,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
   <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
<% end %>
<div id="filterrific_results">
<%= render(
  partial: 'complaints/list',
  locals: { complaints: @complaints }
) %>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_complaint_path,
            :class => 'btn btn-primary' %>

app/views/complaints/index.js.erb
<% js = escape_javascript(
  render(partial: 'complaints/list', locals: { complaints: @complaints })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/complaints/new.html.erb
<%- model_class = Complaint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/complaints/show.html.erb
<%- model_class = Complaint -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:subject) %>:</strong></dt>
  <dd><%= @complaint.subject %></dd>
  <dt><strong><%= model_class.human_attribute_name(:matter) %>:</strong></dt>
  <dd><%= @complaint.matter %></dd>
  <dt><strong><%= model_class.human_attribute_name(:key_words) %>:</strong></dt>
  <dd><%= @complaint.key_words %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              complaints_path, "data-no-turbolink" => true, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_complaint_path(@complaint), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              complaint_path(@complaint),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omniauth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <div class="container">
    <div class="row">
        <div class="span12">
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          </li>
          <% else %>
          <li>
          <%= link_to('Login', new_user_session_path)  %>  
          </li>
        <% end %>
        <%= yield %>
        </div>
    </div>
  </div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>